### ISSUE TITLE
CruxQuickStart generates projects missing classes

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#255]
_From [*adriano...@cruxframework.org](https://code.google.com/u/115398515620387930750/) on June 13, 2011 19:58:53_

java.lang.ClassNotFoundException: org.mortbay.jetty.plus.webapp.EnvConfiguration    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)   at java.security.AccessController.doPrivileged(Native Method)   at java.net.URLClassLoader.findClass(URLClassLoader.java:190)   at java.lang.ClassLoader.loadClass(ClassLoader.java:307)    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)    at org.mortbay.util.Loader.loadClass(Loader.java:91)    at org.mortbay.util.Loader.loadClass(Loader.java:71)    at org.mortbay.jetty.webapp.WebAppContext.loadConfigurations(WebAppContext.java:837)    at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:417)   at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:461)     at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)     at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)    at org.mortbay.jetty.handler.RequestLogHandler.doStart(RequestLogHandler.java:115)  at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)     at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)    at org.mortbay.jetty.Server.doStart(Server.java:222)    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)     at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:565)   at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:494)     at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:1058)    at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:800)     at com.google.gwt.dev.DevMode.main(DevMode.java:304)

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=255_

**Comment by admtriggo** [comment]
_From [ge...@cruxframework.org](https://code.google.com/u/108728025643241132101/) on June 14, 2011 11:15:29_

This is caused because you are using an old version of crux-dev-deps.jar
We still have no place to store this jar, but soon we'll create a maven repository for Crux artifacts.

**Status:** Accepted

**Comment by admtriggo** [comment]
_From [thi...@cruxframework.org](https://code.google.com/u/114650528804514463329/) on December 09, 2013 12:04:42_

Crux Quickstart project was discontinued on Crux 5. We are now using maven archetypes to generate projects based on Crux.

**Status:** WontFix  
  **Owner:** thi...@cruxframework.org
