### ISSUE TITLE
AppcacheFilter throws IllegalArgumentException on Jetty 8

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#472]
_From [alexan...@triggolabs.com](https://code.google.com/u/114384922929308053156/) on August 20, 2014 12:26:50_

StackTrace:

java.lang.IllegalStateException: NO CONTENT
        at org.eclipse.jetty.http.HttpGenerator.addContent(HttpGenerator.java:176)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:155)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:117)
        at org.cruxframework.crux.core.server.http.GZIPResponseStream.close(GZIPResponseStream.java:60)
        at org.cruxframework.crux.core.server.offline.AppcacheFilter$ResponseWrapper$ModifiedOutputStream.close(AppcacheFilter.java:305)
        at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
        at sun.nio.cs.StreamEncoder.close(Unknown Source)
        at java.io.OutputStreamWriter.close(Unknown Source)
        at java.io.PrintWriter.close(Unknown Source)
        at org.cruxframework.crux.core.server.offline.AppcacheFilter$ResponseWrapper.finishResponse(AppcacheFilter.java:250)
        at org.cruxframework.crux.core.server.offline.AppcacheFilter.sendRequestedFile(AppcacheFilter.java:182)
        at org.cruxframework.crux.core.server.offline.AppcacheFilter.doFilter(AppcacheFilter.java:72)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Unknown Source)

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=472_

**Comment by admtriggo** [comment]
_From [alexan...@triggolabs.com](https://code.google.com/u/114384922929308053156/) on August 20, 2014 11:20:34_

trunk. rev5465
branch. rev5467

**Status:** Fixed  
  **Labels:** TargetVersion-5.2.0

**Comment by admtriggo** [comment]
_From [juli...@cruxframework.org](https://code.google.com/u/108392056359000771618/) on August 25, 2014 13:52:48_

**Labels:** -Milestone-5.3 Milestone-2014-04

**Comment by admtriggo** [comment]
_From [juli...@cruxframework.org](https://code.google.com/u/108392056359000771618/) on August 26, 2014 09:05:19_

**Labels:** -Milestone-2014-04 Milestone-M14-C4

**Comment by admtriggo** [comment]
_From [alexan...@triggolabs.com](https://code.google.com/u/114384922929308053156/) on August 27, 2014 10:23:40_

**Labels:** -TargetVersion-5.2.0 -Milestone-M14-C4 TargetVersion-5.1.3 Milestone-M14-C3
