### ISSUE TITLE
Crux SuperDevMode not working with Crux Offline

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#516]
_From [samuel@cruxframework.org](https://code.google.com/u/samuel@cruxframework.org/) on September 08, 2014 18:43:32_

If I try to open an offline index.html file I get this exception:

java.lang.NullPointerException
at org.cruxframework.crux.core.declarativeui.DeclarativeUIScreenResolver.getRootView(DeclarativeUIScreenResolver.java:133)
at org.cruxframework.crux.core.declarativeui.DeclarativeUIScreenResolver.getScreenResource(DeclarativeUIScreenResolver.java:153)
at org.cruxframework.crux.core.declarativeui.filter.DeclarativeUIFilter.doFilter(DeclarativeUIFilter.java:87)

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=516_

**Comment by admtriggo** [comment]
_From [alexan...@triggolabs.com](https://code.google.com/u/114384922929308053156/) on September 18, 2014 12:52:24_

**Labels:** -Milestone-M14-C4 Milestone-M14-C3
