### ISSUE TITLE
Error when using inherit image resource

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#580]
_From [alexandr...@triggolabs.com](https://code.google.com/u/115876322122119724331/) on December 11, 2014 19:59:57_

Use an image resource URL from a parent interface causes this error:

Caused by: org.cruxframework.crux.core.rebind.CruxGeneratorException: Resource [siteResources] , declared on view [home], has an invalid expression [iconFacebook]
at org.cruxframework.crux.core.rebind.screen.widget.ViewFactoryCreator.getResourceAccessExpression(ViewFactoryCreator.java:601)
at org.cruxframework.crux.core.rebind.screen.widget.WidgetCreator.getResourceAccessExpression(WidgetCreator.java:451)
at org.cruxframework.crux.widgets.rebind.image.ImageFactory$URLAttributeParser.processAttribute(ImageFactory.java:58)
at org.cruxframework.crux.core.rebind.screen.widget.AttributeProcessor.processAttributeInternal(AttributeProcessor.java:65)
... 132 more
Caused by: java.lang.NoSuchFieldException: iconFacebook
at org.cruxframework.crux.core.utils.JClassUtils.buildGetValueExpression(JClassUtils.java:101)
at org.cruxframework.crux.core.rebind.screen.widget.ViewFactoryCreator.getResourceAccessExpression(ViewFactoryCreator.java:597)
... 135 more
   [ERROR] Errors in 'org/cruxframework/crux/core/client/screen/views/ViewContainer.java'
      [ERROR] Line 197: Failed to resolve 'org.cruxframework.crux.core.client.screen.views.ViewFactory' via deferred binding
   [WARN] For the following type(s), generated source was never committed (did you forget to call commit()?)
      [WARN] org.cruxframework.crux.core.client.screen.views.ViewFactory_Impl_largeDisplayMouse
      [WARN] org.cruxframework.crux.core.client.screen.views.home_largeDisplayMouse
[ERROR] Compiler returned false
[WARN] continuing to serve previous version

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=580_

**Comment by admtriggo** [comment]
_From [thi...@cruxframework.org](https://code.google.com/u/114650528804514463329/) on February 11, 2015 07:40:32_

Revision r5915

**Status:** Fixed  
  **Labels:** Milestone-M14-C4
