### ISSUE TITLE
Exception occurs on HotDeploymentScanner when a template file is changed

### ISSUE THREAD

**Issue by admtriggo** [CruxFramework/crux#590]
_From [alexandr...@triggolabs.com](https://code.google.com/u/115876322122119724331/) on January 29, 2015 15:38:03_

Exception occurs on HotDeploymentScanner when a template file is changed. Example below:

Error parsing file: [piramide] for DeviceAdaptive interface [largeDisplayMouse]: Template not found. Library: [ssg]. Template: [crudSectionTramitacao].
org.cruxframework.crux.core.declarativeui.template.TemplateException: Template not found. Library: [ssg]. Template: [crudSectionTramitacao].
    at org.cruxframework.crux.core.declarativeui.template.TemplatesPreProcessor.preprocessTemplate(TemplatesPreProcessor.java:288)
    at org.cruxframework.crux.core.declarativeui.template.TemplatesPreProcessor.preprocess(TemplatesPreProcessor.java:206)
    at org.cruxframework.crux.core.declarativeui.template.TemplatesPreProcessor.preprocess(TemplatesPreProcessor.java:187)
    at org.cruxframework.crux.core.declarativeui.template.TemplatesPreProcessor.preprocess(TemplatesPreProcessor.java:97)
    at org.cruxframework.crux.core.declarativeui.ViewProcessor.preprocess(ViewProcessor.java:264)
    at org.cruxframework.crux.core.declarativeui.ViewProcessor.loadCruxPage(ViewProcessor.java:246)
    at org.cruxframework.crux.core.declarativeui.ViewProcessor.getView(ViewProcessor.java:74)
    at org.cruxframework.crux.core.rebind.screen.ViewFactory.getView(ViewFactory.java:102)
    at org.cruxframework.crux.core.rebind.AbstractInterfaceWrapperProxyCreator.findViews(AbstractInterfaceWrapperProxyCreator.java:304)
    at org.cruxframework.crux.core.rebind.AbstractInterfaceWrapperProxyCreator.findViews(AbstractInterfaceWrapperProxyCreator.java:276)
    at org.cruxframework.crux.core.rebind.AbstractInterfaceWrapperProxyCreator.getViews(AbstractInterfaceWrapperProxyCreator.java:221)
    at org.cruxframework.crux.core.rebind.screen.widget.ViewFactoriesProxyCreator.generateCreateViewMethod(ViewFactoriesProxyCreator.java:86)
    at org.cruxframework.crux.core.rebind.screen.widget.ViewFactoriesProxyCreator.generateProxyMethods(ViewFactoriesProxyCreator.java:65)
    at org.cruxframework.crux.core.rebind.AbstractProxyCreator.create(AbstractProxyCreator.java:93)
    at org.cruxframework.crux.core.rebind.AbstractGenerator.generateIncrementally(AbstractGenerator.java:54)
    at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:670)
    at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:41)
    at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
    at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
    at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
    at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:91)
    at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleGwtCreate(UnifyAst.java:387)
    at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:465)
    at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:255)
    at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:244)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:117)
    at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:65)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:117)
    at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:65)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:117)
    at com.google.gwt.dev.jjs.ast.JBinaryOperation.traverse(JBinaryOperation.java:81)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:117)
    at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:41)
    at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:170)
    at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:336)
    at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:83)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:138)
    at com.google.gwt.dev.jjs.ast.JIfStatement.traverse(JIfStatement.java:52)
    at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:170)
    at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:336)
    at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:83)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:138)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:134)
    at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:82)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:449)
    at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:418)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:940)
    at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:665)
    at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:672)
    at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:34)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:271)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:223)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:139)
    at com.google.gwt.dev.Compiler.run(Compiler.java:167)
    at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:115)
    at com.google.gwt.dev.codeserver.Modul...

_Original issue: http://code.google.com/p/crux-framework/issues/detail?id=590_

**Comment by admtriggo** [comment]
_From [samuel@cruxframework.org](https://code.google.com/u/samuel@cruxframework.org/) on January 30, 2015 09:28:17_

Rev. 5896

**Status:** Fixed  
  **Owner:** samuel@cruxframework.org  
  **Labels:** TargetVersion-5.3.0
